sources:
  - name: bronze
    database : dev
    schema : bronze
    tables:
        - name: products
        - name: orders
        - name: customers
        - name: order_items
        - name: order_payments
        - name: order_reviews
        - name: geolocation
        - name: sellers
        - name: product_category_name_translation
        
          