# config.yaml

source:
  username: '<user_name>'
  password: '<password>'
  server: '<server_name>'
  database: '<database_name>'

extraction:
  batch_size: 1000
  tables:

    - customers
    - geolocation
    - order_items
    - order_payments
    - order_reviews
    - orders
    - product_category_name_translation
    - products
    - sellers
   

output:
  target_location: '<target folder>'

