{{
    config(
        materialized='incremental',
        unique_key='order_id'
    )
}}

with orders_data as(
SELECT  
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    CAST(ORDER_PURCHASE_TIMESTAMP AS TIMESTAMP) AS ORDER_PURCHASE_TIMESTAMP,
    CAST(ORDER_APPROVED_AT AS TIMESTAMP) AS ORDER_APPROVED_AT,
    CAST(ORDER_DELIVERED_CARRIER_DATE AS TIMESTAMP) AS ORDER_DELIVERED_CARRIER_DATE,
    CAST(ORDER_DELIVERED_CUSTOMER_DATE AS TIMESTAMP) AS ORDER_DELIVERED_CUSTOMER_DATE,
    CAST(ORDER_ESTIMATED_DELIVERY_DATE AS TIMESTAMP) AS ORDER_ESTIMATED_DELIVERY_DATE,
    CAST(OPERATION AS INT)AS OPERATION,
	CAST(TRANSACTION_TIME AS TIMESTAMP) AS TRANSACTION_TIME
FROM
    {{source('bronze','orders')}} 
),

orders_clean_data as(
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP,
    COALESCE(ORDER_APPROVED_AT::text, 'N/A') as ORDER_APPROVED_AT,
    COALESCE(ORDER_DELIVERED_CARRIER_DATE::text, 'N/A') as ORDER_DELIVERED_CARRIER_DATE,
    COALESCE(ORDER_DELIVERED_CUSTOMER_DATE::text, 'N/A') as ORDER_DELIVERED_CUSTOMER_DATE,
    ORDER_ESTIMATED_DELIVERY_DATE,
    OPERATION,
	TRANSACTION_TIME

FROM 
    orders_data
)

SELECT DISTINCT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP,
    ORDER_APPROVED_AT,
    ORDER_DELIVERED_CARRIER_DATE,
    ORDER_DELIVERED_CUSTOMER_DATE,
    ORDER_ESTIMATED_DELIVERY_DATE
FROM 
    orders_clean_data
{% if is_incremental() %}
  where TRANSACTION_TIME > (select max(TRANSACTION_TIME) from {{ this }})
{% endif %}

