SELECT  
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    CAST(ORDER_PURCHASE_TIMESTAMP AS TIMESTAMP) AS ORDER_PURCHASE_TIMESTAMP,
    CAST(ORDER_APPROVED_AT AS DATETIME) AS ORDER_APPROVED_AT,
    CAST(ORDER_DELIVERED_CARRIER_DATE AS DATETIME) AS ORDER_DELIVERED_CARRIER_DATE,
    CAST(ORDER_DELIVERED_CUSTOMER_DATE AS DATETIME) AS ORDER_DELIVERED_CUSTOMER_DATE,
    CAST(ORDER_ESTIMATED_DELIVERY_DATE AS DATETIME) AS ORDER_ESTIMATED_DELIVERY_DATE,
    INSERTED_AT as INSERTED_AT
FROM
    {{source('bronze','orders')}} 

