SELECT  
    PRODUCT_ID ,
    PRODUCT_CATEGORY_NAME,
    PRODUCT_NAME_LENGTH,
    CAST(PRODUCT_DESCRIPTION_LENGTH AS INT)AS PRODUCT_DESCRIPTION_LENGTH,
    CAST(PRODUCT_PHOTOS_QTY AS INT)AS PRODUCT_PHOTOS_QTY,
    CAST(PRODUCT_WEIGHT_G AS INT)AS PRODUCT_WEIGHT_G,
    CAST(PRODUCT_LENGTH_CM AS INT)AS PRODUCT_LENGTH_CM,
    CAST(PRODUCT_HEIGHT_CM AS INT)AS PRODUCT_HEIGHT_CM,
    CAST(PRODUCT_WIDTH_CM AS INT)AS PRODUCT_WIDTH_CM,
    INSERTED_AT AS INSERTED_AT
FROM
    {{    source ('bronze','products')   }} 
